### ISSUE TITLE
Revert PR #3 (VS runtime 2015 pinning)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyro4-feedstock#5]
Due to a problem with one of the VS runtime 2015 packages, we needed to pin the version specifically ( https://github.com/conda-forge/staged-recipes/issues/666 ). It has since been resolved so this pinning added in PR ( https://github.com/conda-forge/pyro4-feedstock/pull/3 ) should be reverted.

**Comment by pelson** [comment]
Done in #4.

**Comment by jakirkham** [comment]
Ooph, sorry, didn't realized this was already solved. Sorry for the noise.
