### ISSUE TITLE
python version dependency conflict? can't install for python 3.6

### ISSUE THREAD

**Issue by irmen** [conda-forge/pyro4-feedstock#8]
@whart222 @Juanlu001 I don't understand why there is no python 3.6 version available:

```
(root) irmen@minty ~/Projects $ conda install -c conda-forge pyro4
Fetching package metadata .........
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - pyro4
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

I am unfamiliar with all the yml files but at least the appveyor.yml seems to mention CONDA_PY 36.  What/how/when/by whom are new conda packages actually built and made available?

**Comment by astrojuanlu** [comment]
For some reason, the Windows and Linux packages were not uploaded (I just
checked the logs).

I'm on vacation now but we would need to rebuild the recipe.

**Comment by irmen** [comment]
How does one "rebuild the recipe"?  And will that also update the Pyro4 version in the recipe?  (the one available in anaconda seems stuck at 4.43)

**Comment by astrojuanlu** [comment]
Then the easiest thing to do is to open a new PR with the most recent version, as explained in

https://github.com/conda-forge/pyro4-feedstock#updating-pyro4-feedstock

**Comment by irmen** [comment]
I've managed to successfully update the Pyro4 version available with conda and it with that it also installs again on python 3.6 👍
